Parameters:
  USWest2BucketName:
    Type: String
    Default: ka-me-ha-me-ha
    Description: "Name of the bucket to be made in us-west-2"

  APSouth1BucketName:
    Type: String
    Default: ka-me-ha-me-ha
    Description: "Name of the bucket to be made in us-west-2"

Resources:
  USWest2EnablerLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      RoleName: KaMeHaMeHa-us-west-2-Enabler-Lambda-Execution-Role
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  USWest2EnablerLambdaExecutionRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - s3:PutObject
              - s3:GetObject
            Resource: "*"
          - Effect: "Allow"
            Resource: "*"
            Action:
              - "dynamodb:ListStreams"
              - "dynamodb:DescribeStream"
              - "dynamodb:GetShardIterator"
              - "dynamodb:GetRecords"
          - Effect: "Allow"
            Action:
              - "kms:Decrypt"
              - "kms:GenerateDataKey"
            Resource: "*"

      PolicyName: KaMeHaMeHa-us-west-2-Enabler-Lambda-Execution-Role-Policy
      Roles:
        - !Ref USWest2EnablerLambdaExecutionRole

  CustomResourceS3ReplicationRuleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      RoleName: KaMeHaMeHa-Custom-Resource-Replication-Rule-Lambda-Role
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  CustomResourceS3ReplicationRulePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - s3:PutReplicationConfiguration
              - s3:GetReplicationConfiguration
              - iam:PassRole
            Resource: "*"
      PolicyName: KaMeHaMeHa-Custom-Resource-S3-Replication-Execution-Role-Policy
      Roles:
        - !Ref CustomResourceS3ReplicationRuleRole

  CustomResourceS3InitializationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      RoleName: KaMeHaMeHa-Custom-Resource-S3-Initialization-Lambda-Role
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  CustomResourceS3InitializationPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
            Resource: "*"

          - Effect: "Allow"
            Action:
              - "kms:Decrypt"
              - "kms:GenerateDataKey"
            Resource: "*"

      PolicyName: KaMeHaMeHa-Custom-Resource-S3-Initialization-Lambda-Role-Policy
      Roles:
        - !Ref CustomResourceS3InitializationRole

  USWest2ToAPSouth1ReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - s3.amazonaws.com
            Action: "sts:AssumeRole"
      RoleName: us-west-2-To-ap-south-1-replication-role
      Policies:
        - PolicyName: Allow-Read-To-Bucket-One-For-Two-Inline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - s3:GetReplicationConfiguration
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${USWest2BucketName}-${AWS::AccountId}-us-west-2-an"

              - Effect: "Allow"
                Action:
                  - s3:GetObjectVersionForReplication
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectVersionTagging
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${USWest2BucketName}-${AWS::AccountId}-us-west-2-an/*"

              - Effect: "Allow"
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateTags
                  - s3:ReplicateDelete
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${APSouth1BucketName}-${AWS::AccountId}-ap-south-1-an/*"
                
              - Effect: "Allow"
                Action:
                  - "kms:Encrypt"
                  - "kms:GenerateDataKey"
                Resource:
                  - "arn:aws:kms:ap-south-1:295345165437:key/mrk-7c909992068e46948475911fedb1484e"
              
              - Effect: "Allow"
                Action:
                  - "kms:Decrypt"
                Resource:
                  - "arn:aws:kms:us-west-2:295345165437:key/mrk-7c909992068e46948475911fedb1484e"

  APSouth1ToUSWest2ReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - s3.amazonaws.com
            Action: "sts:AssumeRole"
      RoleName: ap-south-1-to-us-west-2-replication-role
      Policies:
        - PolicyName: Allow-Read-To-Bucket-Two-For-One-Inline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - s3:GetReplicationConfiguration
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${APSouth1BucketName}-${AWS::AccountId}-ap-south-1-an"

              - Effect: "Allow"
                Action:
                  - s3:GetObjectVersionForReplication
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectVersionTagging
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${APSouth1BucketName}-${AWS::AccountId}-ap-south-1-an/*"

              - Effect: "Allow"
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateTags
                  - s3:ReplicateDelete
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${USWest2BucketName}-${AWS::AccountId}-us-west-2-an/*"
              
              - Effect: "Allow"
                Action:
                  - "kms:Encrypt"
                  - "kms:GenerateDataKey"
                Resource:
                  - "arn:aws:kms:us-west-2:295345165437:key/mrk-7c909992068e46948475911fedb1484e"
              
              - Effect: "Allow"
                Action:
                  - "kms:Decrypt"
                Resource:
                  - "arn:aws:kms:ap-south-1:295345165437:key/mrk-7c909992068e46948475911fedb1484e"

  USWest2EnablerLambdaExecutionRoleArnSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/internship/tasks/ka-me-ha-me-ha/global/iam/lambda-execution-roles/enabler-arn"
      Value: !GetAtt USWest2EnablerLambdaExecutionRole.Arn
      Type: String
      Tier: Standard

  CustomResourceS3ReplicationRoleArnSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/internship/tasks/ka-me-ha-me-ha/global/iam/lambda-execution-roles/custom-resources/s3-replication-rule-execution-role-arn"
      Value: !GetAtt CustomResourceS3ReplicationRuleRole.Arn
      Type: String
      Tier: Standard

  CustomResourceS3InitializationRoleArnSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/internship/tasks/ka-me-ha-me-ha/global/iam/lambda-execution-roles/custom-resources/s3-initialization-execution-role-arn"
      Value: !GetAtt CustomResourceS3InitializationRole.Arn
      Type: String
      Tier: Standard

  USWest2ToAPSouth1ReplicationRoleArnSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/internship/tasks/ka-me-ha-me-ha/global/iam/bucket-replication-roles/us-west-2-to-ap-south-1"
      Value: !GetAtt USWest2ToAPSouth1ReplicationRole.Arn
      Type: String

  APSouth1ToUSWest2ReplicationRoleArnSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/internship/tasks/ka-me-ha-me-ha/global/iam/bucket-replication-roles/ap-south-1-to-us-west-2"
      Value: !GetAtt APSouth1ToUSWest2ReplicationRole.Arn
      Type: String

Outputs:
  EnablerLambdaFunctionExecutionRoleName:
    Description: "Execution Role Name of Ka-Me-Ha-Me-Ha-Enabler Lambda function"
    Value: !Ref USWest2EnablerLambdaExecutionRole
    Export:
      Name: kamehameha-us-west-2-enabler-lambda-function-role-name

  EnablerLambdaFunctionExecutionRoleArn:
    Description: "Execution Role arn of Ka-Me-Ha-Me-Ha-Enabler Lambda function"
    Value: !GetAtt USWest2EnablerLambdaExecutionRole.Arn
    Export:
      Name: kamehameha-us-west-2-enabler-lambda-function-role-arn

  CustomResourceS3ReplicationRuleExecutionRoleName:
    Description: "Execution Role Name of Custom Resource for s3 replication role Lambda function"
    Value: !Ref CustomResourceS3ReplicationRuleRole
    Export:
      Name: kamehameha-custom-resource-s3-replication-role-name

  CustomResourceS3ReplicationRuleExecutionRoleArn:
    Description: "Execution Role arn of Custom Resource for s3 replication role Lambda function"
    Value: !GetAtt CustomResourceS3ReplicationRuleRole.Arn
    Export:
      Name: kamehameha-custom-resource-s3-replication-role-arn

  CustomResourceS3InitializationExecutionRoleName:
    Description: "Execution Role Name of Custom Resource for s3 Initialization role Lambda function"
    Value: !Ref CustomResourceS3InitializationRole
    Export:
      Name: kamehameha-custom-resource-s3-initialization-role-name

  CustomResourceS3InitializationExecutionRoleArn:
    Description: "Execution Role arn of Custom Resource for s3 Initialization role Lambda function"
    Value: !GetAtt CustomResourceS3InitializationRole.Arn
    Export:
      Name: kamehameha-custom-resource-s3-initialization-role-arn
