Parameters:
  PrimaryBucketName:
    Type: String
    Description: "Name of the bucket to be made in Primary Region"

  SecondaryBucketName:
    Type: String
    Description: "Name of the bucket to be made in Secondary Region"

  PrimaryKMSKeyArn:
    Type: String
    Description: "Key Deployed in Primary Region"

  SecondaryKMSKeyArn:
    Type: String
    Description: "Key Deployed in Secondary Region"


Resources:
  PrimaryEnablerLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  PrimaryToSecondaryReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - s3.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: Allow-Read-To-Bucket-One-For-Two-Inline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - s3:GetReplicationConfiguration
                  - s3:ListBucket
                Resource:
                  - !Ref PrimaryBucketName

              - Effect: "Allow"
                Action:
                  - s3:GetObjectVersionForReplication
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectVersionTagging
                Resource:
                  - !Ref PrimaryBucketName

              - Effect: "Allow"
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateTags
                  - s3:ReplicateDelete
                Resource:
                  - !Ref SecondaryBucketName
                
              - Effect: "Allow"
                Action:
                  - "kms:Encrypt"
                  - "kms:GenerateDataKey"
                Resource:
                  - !Ref SecondaryKMSKeyArn
              
              - Effect: "Allow"
                Action:
                  - "kms:Decrypt"
                Resource:
                  - !Ref PrimaryKMSKeyArn

  SecondaryToPrimaryReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - s3.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: Allow-Read-To-Bucket-Two-For-One-Inline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - s3:GetReplicationConfiguration
                  - s3:ListBucket
                Resource:
                  - !Ref SecondaryBucketName

              - Effect: "Allow"
                Action:
                  - s3:GetObjectVersionForReplication
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectVersionTagging
                Resource:
                  - !Ref SecondaryBucketName

              - Effect: "Allow"
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateTags
                  - s3:ReplicateDelete
                Resource:
                  - !Ref PrimaryBucketName
              
              - Effect: "Allow"
                Action:
                  - "kms:Encrypt"
                  - "kms:GenerateDataKey"
                Resource:
                  - !Ref PrimaryKMSKeyArn
              
              - Effect: "Allow"
                Action:
                  - "kms:Decrypt"
                Resource:
                  - !Ref SecondaryKMSKeyArn


Outputs:
  EnablerLambdaFunctionExecutionRoleName:
    Description: "Execution Role Name of Ka-Me-Ha-Me-Ha-Enabler Lambda function"
    Value: !Ref PrimaryEnablerLambdaExecutionRole

  EnablerLambdaFunctionExecutionRoleArn:
    Description: "Execution Role arn of Ka-Me-Ha-Me-Ha-Enabler Lambda function"
    Value: !GetAtt PrimaryEnablerLambdaExecutionRole.Arn

  PrimaryToSecondaryReplicationRoleName:
    Description: "Name of Replication Role for the s3 buckets Primary Region -> Secondary Region"
    Value: !Ref PrimaryToSecondaryReplicationRole

  PrimaryToSecondaryReplicationRoleArn:
    Description: "Arn of Replication Role for the s3 buckets Primary Region -> Secondary Region"
    Value: !GetAtt PrimaryToSecondaryReplicationRole.Arn

  SecondaryToPrimaryReplicationRoleName:
    Description: "Name of Replication Role for the s3 buckets Secondary Region -> Primary Region"
    Value: !Ref SecondaryToPrimaryReplicationRole

  SecondaryToPrimaryReplicationRoleArn:
    Description: "Arn of Replication Role for the s3 buckets Secondary Region -> Primary Region"
    Value: !GetAtt SecondaryToPrimaryReplicationRole.Arn

