Parameters:
  CreateReplicaKey:
    Type: String
    AllowedValues: ["True", "False"]
    Default: "False"

  CreateKeys:
    Type: String
    AllowedValues: ["True", "False"]
    Default: "False"

  KMSMainKeyArn:
    Type: String
    Default: "not:set"


Conditions:
  IsCreateReplicaKeyTrue: !And
    - !Equals [!Ref CreateReplicaKey, "True"]
    - !Equals [!Ref CreateKeys, "True"]

  IsCreateMultiRegionKeyTrue: !And
    - !Not
      - Condition: IsCreateReplicaKeyTrue
    - !Equals [!Ref CreateKeys, "True"]


Resources:
  KMSReplicaKey:
    Type: AWS::KMS::ReplicaKey
    Condition: IsCreateReplicaKeyTrue
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      PrimaryKeyArn: !Ref KMSMainKeyArn
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"

  KMSMainKey:
    Type: AWS::KMS::Key
    Condition: IsCreateMultiRegionKeyTrue
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: This Key is for S3 Server Side Encryption - KMS
      MultiRegion: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"


Outputs:
  KMSMainKeyArn:
    Description: "KMS Key ARN for S3 SSE-KMS"
    Condition: IsCreateMultiRegionKeyTrue
    Value: !GetAtt KMSMainKey.Arn

  KMSMainKeyId:
    Description: "KMS Key ID for S3 SSE-KMS"
    Condition: IsCreateMultiRegionKeyTrue
    Value: !GetAtt KMSMainKey.KeyId

  KMSReplicaKeyId:
    Description: "Replica Key Id for S3 SSE-KMS"
    Condition: IsCreateReplicaKeyTrue
    Value: !GetAtt KMSReplicaKey.KeyId

  KMSReplicaKeyArn:
    Description: "Replica Key Arn for S3 SSE-KMS"
    Condition: IsCreateReplicaKeyTrue
    Value: !GetAtt KMSReplicaKey.Arn
