Parameters:
  ExecutionRoleArn:
    Type: String
    Description: "Lambda function execution role arn"
  
  ExecutionRoleName:
    Type: String
    Description: "Lambda function execution role name"
  
  CodeBucket:
    Type: String
    Description: "The bucket containing the code zip file"
  
  CodeZipObjectKey:
    Type: String
    Description: "The object containing the code zip file"
  
  BucketNameEnv:
    Type: String
    Description: "The Environment variable BUCKET_NAME"
  
  ObjectKeyEnv:
    Type: String
    Description: "The Environment variable OBJECT_KEY"
  
  DynamodbStreamArn:
    Type: String
    Description: "Arn of the dynamodb stream"

  KMSKeyArn:
    Type: String
    Description: "Arn of the kms Key"

  LambdaFunctionName:
    Type: String
    Description: "The name of the function"
  

Resources:
  LambdaExecutionRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - s3:PutObject
              - s3:GetObject
            Resource: !Sub "arn:${AWS::Partition}:s3:::${BucketNameEnv}-${AWS::AccountId}-us-west-2-an/*"
          - Effect: "Allow"
            Action:
              - "dynamodb:ListStreams"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "dynamodb:DescribeStream"
              - "dynamodb:GetShardIterator"
              - "dynamodb:GetRecords"
            Resource: !Ref DynamodbStreamArn
          - Effect: "Allow"
            Action:
              - "kms:Decrypt"
              - "kms:GenerateDataKey"
            Resource: !Ref KMSKeyArn
      PolicyName: KaMeHaMeHa-us-west-2-Enabler-Lambda-Execution-Role-Policy
      Roles:
        - !Ref ExecutionRoleName

  EnablerLambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn: LambdaExecutionRolePolicy
    Properties:
      Code: 
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeZipObjectKey
      Role: !Ref ExecutionRoleArn
      FunctionName: !Ref LambdaFunctionName
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketNameEnv
          OBJECT_KEY: !Ref ObjectKeyEnv
      Description: "Task Required lambda function for the s3 bucket object manipulation"
      Runtime: python3.14
      Timeout: 200
      Handler: handler.main
  
  EventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      FunctionName: !Ref EnablerLambdaFunction
      Enabled: true
      EventSourceArn: !Ref DynamodbStreamArn
      StartingPosition: LATEST
      FilterCriteria:
        Filters:
          - Pattern: '{"eventName": ["INSERT", "MODIFY"]}'
