Parameters:
  S3BucketName:
    Description: "Name for bucket One"
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/internship/tasks/ka-me-ha-me-ha/us-west-2/s3/bucket/task-bucket-name"

  LambdaCodeBucket:
    Description: "Bucket with the code of the lambda function"
    Type: String
    Default: cloudformation-us-west-2-templates-295345165437-us-west-2-an
  
  LambdaCodeZipObjectKey:
    Description: "Object key of the zip file for the code"
    Type: String
    Default: kamehameha/main/lambda-zips/custom-resource-s3-initialization.zip

Resources:
  CustomResourceForS3InitializationLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeZipObjectKey
      Role: "{{resolve:ssm:/internship/tasks/ka-me-ha-me-ha/global/iam/lambda-execution-roles/custom-resources/s3-initialization-execution-role-arn}}"
      Handler: handler.main
      Runtime: python3.14
      Timeout: 200
      PackageType: Zip

  BucketInitialization:
    Type: Custom::LambdaReplicationResource
    Properties:
      ServiceToken: !GetAtt CustomResourceForS3InitializationLambdaFunction.Arn
      ServiceTimeout: 200
      BucketName: !Ref S3BucketName
      S3ObjectKey: teenage-mutant-ninja-turtles.json
      JSONKeys:
        - previous
        - current 
      
