Parameters:
  DynamodbTableName:
    Default: ka-me-ha-me-ha-archives
    Type: String

Resources:
  DynamodbTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties: 
      BillingMode: PAY_PER_REQUEST

      TableClass: STANDARD
 
      TableName: !Ref DynamodbTableName
  
      SSESpecification: 
        SSEEnabled: false
 
      StreamSpecification:
        StreamViewType: NEW_IMAGE 

      AttributeDefinitions:
        - AttributeName: "Attacker"
          AttributeType: "S"
        - AttributeName: "Defender"
          AttributeType: "S"

      KeySchema:
        - AttributeName: "Attacker"
          KeyType: HASH
        - AttributeName: "Defender"
          KeyType: RANGE

Outputs:
  
  DynamoDBTableArn:
    Description: "The arn of the dynamodb table ka-me-ha-me-ha-archives"
    Value: !GetAtt DynamodbTable.Arn
    Export: 
      Name: kamehameha-us-west-2-dynamdb-table-arn
  
  
  DynamoDBTableStreamArn:
    Description: "The arn of the ka-me-ha-me-ha-archives table DynamodbStream"
    Value: !GetAtt DynamodbTable.StreamArn
    Export: 
      Name: kamehameha-us-west-2-dynamdb-stream-arn
  

