Parameters:
  CreateMultiRegionKey:
    Type: String
    AllowedValues: ["True", "False"]
    Default: "False"

Conditions:
  IsCreateMultiRegionKeyTrue: !Equals [!Ref CreateMultiRegionKey, 'True']

Resources:
  KMSMainKey:
    Type: AWS::KMS::Key
    Condition: IsCreateMultiRegionKeyTrue
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: This Key is for S3 Server Side Encryption - KMS
      MultiRegion: true
      Tags:
          - Key: task
            Value: Ka-Me-Ha-Me-Ha

  KMSMainKeyArnOutputToParameterStore:
    Type: AWS::SSM::Parameter
    Condition: IsCreateMultiRegionKeyTrue
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: "/internship/tasks/ka-me-ha-me-ha/us-west-2/kms/sse-multi-region-key/arn"
      Value: !GetAtt KMSMainKey.Arn
      Type: String
      Tier: Standard
  
  KMSMainKeyIDOutputToParameterStore:
    Type: AWS::SSM::Parameter
    Condition: IsCreateMultiRegionKeyTrue
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: "/internship/tasks/ka-me-ha-me-ha/us-west-2/kms/sse-multi-region-key/id"
      Value: !GetAtt KMSMainKey.KeyId
      Type: String
      Tier: Standard
    
Outputs:
    
  KMSMainKeyArnOutput:
    Description: KMS Key ARN for S3 SSE-KMS
    Condition: IsCreateMultiRegionKeyTrue
    Value: !GetAtt KMSMainKey.Arn
    Export: 
      Name: kamehameha-us-west-2-kms-multi-region-key-arn

  KMSMainKeyIdOutput:
    Description: KMS Key ID for S3 SSE-KMS
    Condition: IsCreateMultiRegionKeyTrue
    Value: !GetAtt KMSMainKey.KeyId
    Export: 
      Name: kamehameha-us-west-2-kms-multi-region-key-id

