Parameters:
  
  DynamodbTemplateURL:
    Type: String
    Default: "https://cloudformation-us-west-2-templates-295345165437-us-west-2-an.s3.us-west-2.amazonaws.com/kamehameha/templates/DynamoDB.yaml"
    Description: "Template url of DynamoDB Resource"

  BucketTemplateUrl:
    Type: String
    Default: "https://cloudformation-us-west-2-templates-295345165437-us-west-2-an.s3.us-west-2.amazonaws.com/kamehameha/templates/S3.yaml"
    Description: "Template url of s3 bucket"

  LambdaFunctionTemplateUrl:
    Type: String
    Default: "https://cloudformation-us-west-2-templates-295345165437-us-west-2-an.s3.us-west-2.amazonaws.com/kamehameha/templates/Lambda.yaml"
    Description: "Template url of enabler lambda function"
  
  SSEKMSKeyTemplateUrl:
    Type: String
    Default: "https://cloudformation-us-west-2-templates-295345165437-us-west-2-an.s3.us-west-2.amazonaws.com/kamehameha/templates/KMS-Main-Key.yaml"
    Description: "Template url of sse-kms-multi-region-key"
  
  CustomResourceTemplateUrl:
    Type: String
    Default: "https://cloudformation-us-west-2-templates-295345165437-us-west-2-an.s3.us-west-2.amazonaws.com/kamehameha/templates/S3-intialization-Custom-Resource.yaml"
    Description: "Template url of custom resource"
  
  CreateKMSKey:
    Type: String
    Default: "False"
    AllowedValues: ["True", "False"]
    Description: "Make Server Side Encryption Key?"

Resources:
  
  KMSMultiRegionKeyForSSEKMS:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Ref SSEKMSKeyTemplateUrl
      Parameters:
        CreateMultiRegionKey : !Ref CreateKMSKey
  
  DynamoDBTableWithStream:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Ref DynamodbTemplateURL
  
  USWest2S3Bucket:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    DependsOn: KMSMultiRegionKeyForSSEKMS
    Properties:
      TemplateURL: !Ref BucketTemplateUrl
      
  EnablerLambdaFunction:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Ref LambdaFunctionTemplateUrl
      Parameters:
        DynamodbStreamArn: !GetAtt DynamoDBTableWithStream.Outputs.DynamoDBTableStreamArn
        EnablerLambdaFunctionEnvBucketName: !GetAtt USWest2S3Bucket.Outputs.USWest2S3BucketName
        EnablerLambdaFunctionEnvObjectKey: teenage-mutant-ninja-turtles.json

      
  CustomResource:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Ref CustomResourceTemplateUrl
      Parameters:
        S3BucketName: !GetAtt USWest2S3Bucket.Outputs.USWest2S3BucketName
      