Parameters:
    
  CreateKMSReplicaKey:
    Type: String
    Default: "False"
    AllowedValues: ["True", "False"]
    Description: "Make Server Side Encryption Key?"
  
  ReplicaKeyTemplateUrl:
    Type: String
    Default: "https://cloudformation-ap-south-1-templates-295345165437-ap-south-1-an.s3.ap-south-1.amazonaws.com/kamehameha/main/ap-south-1/KMS-Replica-Key.yaml"
    Description: "S3 Url of the template for Replica Key"

  S3BucketTemplateUrl:
    Type: String
    Default: "https://cloudformation-ap-south-1-templates-295345165437-ap-south-1-an.s3.ap-south-1.amazonaws.com/kamehameha/main/ap-south-1/S3.yaml"
    Description: "S3 Url of the template for the S3 bucket"
  
  GetParametersTemplateUrl:
    Type: String
    Default: "https://cloudformation-ap-south-1-templates-295345165437-ap-south-1-an.s3.ap-south-1.amazonaws.com/kamehameha/main/ap-south-1/get-parameters.yaml"
    Description: "S3 Url of the template to read parameters"

Resources:
  
  GetParmeters:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Ref GetParametersTemplateUrl
      
  ReplicaKey:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Parameters:
        CreateReplicaKey: !Ref CreateKMSReplicaKey
        KMSMainKeyArn: !GetAtt GetParmeters.Outputs.KMSMainKeyArn
      TemplateURL: !Ref ReplicaKeyTemplateUrl
  
  S3Bucket:
    Type: AWS::CloudFormation::Stack
    DependsOn: ReplicaKey
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Ref S3BucketTemplateUrl 
      Parameters:
        ReplicationBucketArn: !GetAtt GetParmeters.Outputs.ReplicationBucketArn
        ReplicationRole: !GetAtt GetParmeters.Outputs.ReplicationRole
        ReplicationBucketEncryptionKey: !GetAtt GetParmeters.Outputs.KMSMainKeyArn