Parameters:
  SSEKMSKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /internship/tasks/ka-me-ha-me-ha/ap-south-1/kms/sse-multi-region-key/arn
    Description: "Key to be used for server-side-encryption"

  BucketName:
    Type: String
    Description: "Name of the bucket"
    Default: ka-me-ha-me-ha
  
  # Read this
  ReplicationRole:
    Type: String
    Default: "/internship/tasks/ka-me-ha-me-ha/global/iam/bucket-replication-roles/ap-south-1-to-us-west-2"
    Description: "Role S3 will use to replicate to us-west-2 bucket"
  
  # Read this
  ReplicationBucketArn:
    Type: String
    Default: "/internship/tasks/ka-me-ha-me-ha/us-west-2/s3/bucket/task-bucket-arn"
    Description: "The Bucket to replicate to"
  
  ReplicationBucketEncryptionKey:
    Type: String
    Default: "Not Set"
    Description: "The Key used to Encrypt the bucket"

Resources:
  
  APSouth1S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub
        - "${Name}-${AccountID}-${Region}-an"
        - Name: !Ref BucketName
          AccountID: !Ref AWS::AccountId
          Region: !Ref AWS::Region
          
      BucketNamespace: account-regional
      
      VersioningConfiguration:
        Status: Enabled

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref SSEKMSKey
      
      ReplicationConfiguration:
        Role: !Ref ReplicationRole
        Rules:
          - Destination:
              Bucket: !Ref ReplicationBucketArn
              EncryptionConfiguration:
                ReplicaKmsKeyID: !Ref ReplicationBucketEncryptionKey
            Status: Enabled
            Filter:
              Prefix: ""
            Priority: 1
            DeleteMarkerReplication: 
              Status: Enabled
            SourceSelectionCriteria:
              SseKmsEncryptedObjects:
                Status: Enabled
  
  APSouth1S3BucketNameSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/internship/tasks/ka-me-ha-me-ha/ap-south-1/s3/bucket/task-bucket-bucket_name"
      Value: !Ref APSouth1S3Bucket
      Type: String
  
  APSouth1S3BucketArnSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/internship/tasks/ka-me-ha-me-ha/ap-south-1/s3/bucket/task-bucket-arn"
      Value: !GetAtt APSouth1S3Bucket.Arn
      Type: String
